<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFBec1nd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFBec1nd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFBec1nd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFBec1nd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFBec1nd\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FBec1nd',
    'container.build_id' => 'bc5cdca1',
    'container.build_time' => 1529000338,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFBec1nd');
